version: '3.8'

services:
  weather_app:
    build: .
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./static:/app/static
      - ./templates:/app/templates
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8083", "--reload", "--log-level", "debug"]
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1 